# Generated by Django 3.2 on 2022-05-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('content', models.TextField(verbose_name='Content')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Contact Request Date')),
            ],
            options={
                'verbose_name': 'Contact Request',
                'verbose_name_plural': 'Contact Requests',
                'ordering': (('-date',),),
            },
        ),
    ]
