# Generated by Django 3.2 on 2022-05-11 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactrequest',
            options={'ordering': ('-date',), 'verbose_name': 'Contact Request', 'verbose_name_plural': 'Contact Requests'},
        ),
    ]
