# Generated by Django 3.2 on 2022-05-11 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Article Title')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Content')),
                ('publication_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Publish Date and Time')),
                ('is_online', models.BooleanField(default=False, verbose_name='Make it Online')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Article Author')),
            ],
            options={
                'ordering': ('-publication_datetime',),
            },
        ),
    ]
