# Generated by Django 3.2 on 2022-05-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0002_alter_article_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-publication_datetime',), 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
