# Generated by Django 3.2 on 2022-05-11 22:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0004_auto_20220511_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publish Date and Time'),
        ),
    ]
